/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrientadorPerfilRouteImport } from './routes/orientador.perfil'
import { Route as OrientadorPainelRouteImport } from './routes/orientador.painel'
import { Route as AlunoPerfilRouteImport } from './routes/aluno.perfil'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrientadorPerfilRoute = OrientadorPerfilRouteImport.update({
  id: '/orientador/perfil',
  path: '/orientador/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OrientadorPainelRoute = OrientadorPainelRouteImport.update({
  id: '/orientador/painel',
  path: '/orientador/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoPerfilRoute = AlunoPerfilRouteImport.update({
  id: '/aluno/perfil',
  path: '/aluno/perfil',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/orientador/painel': typeof OrientadorPainelRoute
  '/orientador/perfil': typeof OrientadorPerfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/orientador/painel': typeof OrientadorPainelRoute
  '/orientador/perfil': typeof OrientadorPerfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/orientador/painel': typeof OrientadorPainelRoute
  '/orientador/perfil': typeof OrientadorPerfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buscar'
    | '/cadastro'
    | '/login'
    | '/aluno/perfil'
    | '/orientador/painel'
    | '/orientador/perfil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/cadastro'
    | '/login'
    | '/aluno/perfil'
    | '/orientador/painel'
    | '/orientador/perfil'
  id:
    | '__root__'
    | '/'
    | '/buscar'
    | '/cadastro'
    | '/login'
    | '/aluno/perfil'
    | '/orientador/painel'
    | '/orientador/perfil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscarRoute: typeof BuscarRoute
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  AlunoPerfilRoute: typeof AlunoPerfilRoute
  OrientadorPainelRoute: typeof OrientadorPainelRoute
  OrientadorPerfilRoute: typeof OrientadorPerfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orientador/perfil': {
      id: '/orientador/perfil'
      path: '/orientador/perfil'
      fullPath: '/orientador/perfil'
      preLoaderRoute: typeof OrientadorPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orientador/painel': {
      id: '/orientador/painel'
      path: '/orientador/painel'
      fullPath: '/orientador/painel'
      preLoaderRoute: typeof OrientadorPainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/perfil': {
      id: '/aluno/perfil'
      path: '/aluno/perfil'
      fullPath: '/aluno/perfil'
      preLoaderRoute: typeof AlunoPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscarRoute: BuscarRoute,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  AlunoPerfilRoute: AlunoPerfilRoute,
  OrientadorPainelRoute: OrientadorPainelRoute,
  OrientadorPerfilRoute: OrientadorPerfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
